import = [
    "~/.config/alacritty/themes/themes/gruvbox_material.toml"
]

[colors.bright]
black = "0x45403d"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.normal]
black = "0x45403d"
blue = "0x7daea3"
cyan = "0x89b482"
green = "0xa9b665"
magenta = "0xd3869b"
red = "0xea6962"
white = "0xd4be98"
yellow = "0xd8a657"

[colors.primary]
background = "0x32302f"
foreground = "0xd4be98"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono NFM"
style = "Bold"

[font.normal]
family = "JetBrainsMono NFM"
style = "Regular"

[font.offset]
x = 0
y = 1

[[keyboard.bindings]]
chars = "\u001F"
key = "Minus"
mods = "Control"

[shell]
args = ["--login"]
program = "/usr/bin/zsh"

[window]
decorations = "none"
startup_mode = "Fullscreen"
